### PR TITLE
fixed the broken TOC issue; also added the 2020 updates

### PR DESCRIPTION
**Pull request by grapesmoker**
This PR fixes a problem in Reg C where trying to do a diff resulted in a 500 error. The culprit was the following element, which can be found in `2011-31712.xml`:

```
<tocInterpEntry target="1003-Interp-h1">
   <interpTitle>Introduction</interpTitle>
</tocInterpEntry>
```

This is partially the result of some implicit magic that happens inside regsite where it tries to figure out if an intro paragraph exists and if it does, it adds that introduction to the ToC. A much more reasonable thing to do would be to explicitly have or not have such a thing in the ToC as necessary, which is what I foolishly did, forgetting about the wizardry of ToC construction. I have now removed this offending entry and verified that it works locally.

This can be tested by checking out the files and then running

`./regml.py json-through 12 1003` from the `regulations-xml-parser` project (you don't need to run `apply-through` because the change was only made to the initial regulation version). Once the JSON is generated, import it into regcore using

`./send_to.py -r 1003 -s <path-to-regulations-stub> -a http://localhost:8181/demo-api` (assuming your regcore is running on 8181).

This PR also corrects the part of `2015-26607` that becomes effective on 2020-01-01.

### CODE REVIEW

**Comment by chosak** [comment]
FYI, the Travis CI push failure seems to be an issue with the RegML validation logic and can be ignored/should be addressed outside of this PR. You can see that the PR test passed and seems to have validated all of the RegML properly.

> This PR also corrects the part of 2015-26607 that becomes effective on 2020-01-01

Can you say a little more about this? What corrections were needed here?

**Comment by grapesmoker** [comment]
Actually it turns out that I'm not done with the fixes. Basically I needed to fix the ToC for this notice and there were missing definitions but I found out that I wasn't done with those. There should be a few more commits to fix this soon.

**Comment by grapesmoker** [comment]
Ok, the last few commits fix some problems I didn't even realize I had. First, there were some missing ToC entries in the latter notices because I had failed to update the ToC to correspond to changes that were made in `2015-26607_20180101`. That is now fixed, the sections have the correct headings, and the link to Appendix C is in the ToC. Also, I had somehow missed that the paragraph structure in Appendix A was broken, resulting in the wrong markers being displayed. That is also now fixed and it can be seen that the markers are in the proper order.

**Review by chosak — APPROVED** [review]
This looks good to me. Is there anything we can do to be more consistent about linking internal references? For example, in the 2020 version, at 1003.5(a)(1)(ii), there's this missing link:

image

**Comment by grapesmoker** [comment]
Good catch. There's a `fix_omitted_cites` function in `regulations-xml-parser` and I have added some functionality to run it from the command line. I'll have a PR for that, and run it on reg C to fix these missing links.

**Comment by grapesmoker** [comment]
Just made another commit fixing the missing internal references. My method doesn't catch every one of them, but most are of the form part.section(marker)(marker) etc., so those are caught.

**Comment by chosak** [comment]
Very cool!

**Pull request merged**
