### PR TITLE
fixing the issues highlighted in 2033

### PR DESCRIPTION
**Pull request by grapesmoker**
This PR fixes the problems in eRegs-Notes/issues/2033. These are all cosmetic fixes, like adding headers to paragraphs that should have them and fixing typos and such. Testable in the usual way, by running `apply-through` then `json-through`, then loading the resulting JSON into your local.

I'm going to request a review from @niqjohnson, but am unsure if I should also be asking either @willbarton or @chosak, given that they are the other two most knowledgeable-about-eregs people but are not on the project. So I'm tagging them in case they want to contribute without being "officially" asked to review.

### CODE REVIEW

**Comment by grapesmoker** [comment]
Oh, and this PR also creates a branch for _all_ Reg C work; each reg is going to have its own branch from now on, and all work on that reg will be done in that branch before being merged to master, rather than having millions of per-feature branches, which has become unwieldy.

**Review by niqjohnson — COMMENTED** [review]
I glanced through the file changes in GitHub's diff view, and everything looked OK to me. I'm definitely a RegML newbie, though, so I'm not sure if someone else wants to take a look, too.

I also imported all the updates locally to check them in the front end. It looks like these updates fix most of the errors identified during the review save a few:

- Paragraph 7 in the official interpretation for 1003.4(a)(35) isn't numbered
- Some of the official interpretation paragraphs identified as not having a heading in the original review still don't have headings:
    - 1003.2(g) paragraph 3
    - 1003.3(c)(10) paragraph 3
    - 1003.4(a)(1)(i) paragraphs 3 & 4
    - 1003.4(a)(9)(ii)(A) paragraph 1
    - 1003.4(a)(9)(ii)(B) paragraph 2
    - 1003.4(a)(9)(ii)(C) paragraph 2

There's a better-than-even chance that I just didn't do something right to see those changes, though, so let me know if they're showing up locally for you, @grapesmoker.

**Comment by grapesmoker** [comment]
I will go back and review those, thanks.

**Comment by grapesmoker** [comment]
Ok, I confirmed these bugs and have fixed them in the latest commit. There will be a JSON commit shortly as well.

**Review by niqjohnson — APPROVED** [review]
I imported the latest fixes locally, and all the issues from the review look fixed to me now. I've still only skimmed the RegML, so if anyone more versed in RegML wants to take a closer look at that, go for it. Otherwise, looks 👍 to me.

**Pull request merged**
