### PR TITLE
Effective date and fixed ToC for Reg E

### PR DESCRIPTION
**Pull request by grapesmoker**
This PR commits several major changes to Reg E.

1. The effective date of notice 2016-24503 has changed from October 1, 2017, to April 1, 2018.
2. Interps for appendix A have been headerized, meaning that stuff that was in the `<content>` tag that really should have been in a `<title>` is now actually in a title.
3. Changesets have been reworked to properly create a correct table of contents; in order to work, this change needs to be accompanied by the merge from [PR 837](https://github.com/cfpb/regulations-site/pull/837) on regsite.
4. The changes have all been compiled into regulation versions.

### CODE REVIEW

**Comment by chosak** [comment]
@grapesmoker just a minor clarification about this PR. There were [various commits to regulations-stub](https://github.com/cfpb/regulations-stub/commits/master) about a month ago that included changes to Reg E, but I don't see any analogous commits here in regulations-xml. Are those changes (which have already been deployed into production) included in this PR?

**Comment by grapesmoker** [comment]
Yeah, they are part of this PR; those changes were just to address the effective date.

**Comment by chosak** [comment]
Thanks. From looking at the changes to the regs, I can see that the TOC changes from having a `<tocSubpartEntry>` as the main child ([here](https://github.com/cfpb/regulations-xml/pull/29/files?diff=split#diff-0e2fffb90b3fb66423b8387fe9f47851R25)) to having just a `<tocAppEntry>` as the main child ([here](https://github.com/cfpb/regulations-xml/pull/29/files?diff=split#diff-0e2fffb90b3fb66423b8387fe9f47851R139)). Am I misreading this? Why is the main content now treated as an appendix?

(Also, minor thing, but can the commented out sections [like these](https://github.com/cfpb/regulations-xml/pull/29/files?diff=split#diff-0e2fffb90b3fb66423b8387fe9f47851R25) be removed from the RegML?)

**Comment by grapesmoker** [comment]
Oh, sorry about the comments. I thought I'd gotten rid of those.

So, basically, it has to do with the way that the ToC is compiled from the ToCs of the various subparts. It's not that the main content is being treated as an appendix, it's that the stuff that lives in the Subparts (which is now what the main content is), is being pulled from the Subpart TOCs instead of from the main one. It's kind of a weird trick to make it so that when the JSON for the TOC layer is compiled, it has the right form.

**Pull request merged**
