### PR TITLE
Reg Z KBYO

### PR DESCRIPTION
**Pull request by grapesmoker**
This PR commits my work on the KBYO update. I also accidentally committed a minor change to a Reg C notice (it only adds the regulation letter to the preamble), hopefully that won't be a problem. All of these commits are just saving incremental work so that I wouldn't lose it; the final product is the 2017-15764 notice, which is the most recent notice. That notice also has text that comes into effect in April 2018, which I have not split out into a separate notice.

### CODE REVIEW

**Comment by chosak** [comment]
Doesn't this PR also need to add another version of the regulation XML?

**Comment by grapesmoker** [comment]
Yeah, my bad. Will add that.

**Comment by grapesmoker** [comment]
Ok, this last commit is actually quite big so I just want to explain what happened here. Basically, I started trying to compile the last notice (KBYO) and ran into some issues. Most of those were stuff like me mistyping the label or forgetting to write the correct subpath for a change, and that's all fixed in the actual KBYO notice (2017-15764). However, there was one change that wouldn't work because of a typo that occurred way earlier in the notice chain, in notice 2013-28210. There, I accidentally typed a "g" instead of an "i" in a label and it caused problems when trying to modify that label later on. So I changed the label in 2013-28210 and recompiled the whole chain. All of that is in this commit, so even though it looks large, most of it is just a change to that one label that's being propagated downstream into later notices. The major new addition is obviously the compiled form of the KBYO notice itself.

Also, this commit includes an addition to .gitignore that prevents it from committing temporary Emacs files.

**Comment by grapesmoker** [comment]
Can we merge this? No one has registered any objections, and while I do realize that it's a bear of a commit, it's also holding back another PR that I'd like to make for the reg E fixes. All of this content is on build already.

**Comment by chosak** [comment]
How is this holding back the Reg E fixes? Shouldn't the changes be independent?

**Comment by grapesmoker** [comment]
Well, that's because I'm dumb and accidentally polluted my commit history on the other branch and am not sure how to fix it.

**Comment by grapesmoker** [comment]
I would say though that even had I not failed at git, we should still commit this because it's already on build and been reviewed, and it's definitely going to get in the way of any Z changes that I want to make this sprint.

**Comment by chosak** [comment]
I haven't reviewed this in its latest form so will defer to @ascott1 and @niqjohnson as to whether it should be merged; regardless it'd be better to clean up any Reg E branches so that they don't have Reg Z changes mixed in. I can help with git cleanup as needed; if it's just a matter of combining E and Z commits into the same branch then [`git cherry-pick`](https://git-scm.com/docs/git-cherry-pick) might be useful.

**Comment by ascott1** [comment]
Based on the sheer size, the number of commits, and that these changes are visible on the build server I am in favor of merging and moving forward. However, going forward let's keep branches independent and aim to keep PRs smaller in scope.

**Comment by grapesmoker** [comment]
Ok, here's what's happening. I have a few more KBYO changes that need to be pushed; these changes are mostly cosmetic having to do with links displaying correctly. I'm going to push up these changes and merge this PR. It doesn't contain anything from any other regs so it should be clean with respect to other branches. The Reg E stuff that I had accidentally mixed into my Reg Z work has since been broken out into a different branch and PRed/merged. This should bring the XML repository in line with whatever's going on in regulations-stub.

EDIT: Actually I have no changes that need to be made. I was merely confused by the github interface. I'm just merging this now.

**Pull request merged**
