### PR TITLE
Reg E: Missing interpretation drop down boxes #2089

### PR DESCRIPTION
**Pull request by cwdavies**
Reg REG_E
Notice: N/A
Issue(s)
The official interpretations drop down boxes in Reg E are missing see sections 1005.31, 1005.32, 1005.33, 1005.34, 1005.35 and 1005.36 appears to be missing in E-Regs

### CODE REVIEW

**Review by willbarton — COMMENTED** [review]
1005.31, 32, 33, 34, and 36 look good to me. 1005.35 doesn't seem to have its interpretation inline though.

**Comment by cwdavies** [comment]
Please run a git pull and check section 1005.35 in Reg E has an interpretation inline now

**Review by higs4281 — COMMENTED** [review]
I get an interp now for 1005.35

**Review by willbarton — APPROVED** [review]
Me too!

**Comment by cwdavies** [comment]
Made simple prepaid amendment effective date change as requested in:
GHE/eregs/eRegs-Notes/issues/2102
Stakeholder HaywoodJ agreed with suggestion to skip team review so merging branch into master and deploying to build server for stakeholder review.

**Pull request merged**
